// <auto-generated />
using IeasteJson2Svg;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IeasteJson2Svg.Migrations
{
    [DbContext(typeof(DocumentsContainerContext))]
    [Migration("20190803162203_Migration1")]
    partial class Migration1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("IeasteJson2Svg.Models.SvgDocument", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("DocumentName");

                    b.Property<string>("DocumentPath");

                    b.HasKey("ID");

                    b.ToTable("SvgDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
