// <auto-generated />
using IeasteJson2Svg;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IeasteJson2Svg.Migrations
{
    [DbContext(typeof(DocumentsContainerContext))]
    partial class DocumentsContainerContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("IeasteJson2Svg.Models.SvgDocument", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("DocumentName");

                    b.Property<string>("DocumentPath");

                    b.HasKey("ID");

                    b.ToTable("SvgDocuments");
                });

            modelBuilder.Entity("IeasteJson2Svg.Models.SvgElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AttributeInnerText");

                    b.Property<string>("AttributeName");

                    b.Property<int>("DocumentId");

                    b.Property<bool>("IsActive");

                    b.HasKey("Id");

                    b.ToTable("SvgElements");
                });
#pragma warning restore 612, 618
        }
    }
}
